export const UPDATE_CEP = "UPDATE_CEP";
export const CEP_SEARCH_REQUEST = "CEP_SEARCH_REQUEST";
export const CEP_SEARCH_SUCCESS = "CEP_SEARCH_SUCCESS";
export const CEP_SEARCH_NO_RESULTS = "CEP_SEARCH_NO_RESULTS";
export const CEP_SEARCH_FAILURE = "CEP_SEARCH_FAILURE";
